### ISSUE TITLE
Issues with the implementation

### ISSUE THREAD

**Issue by TheOfficialFloW** [Dongdongshe/neuzz#12]
I tried to launch a fuzzing campaign on tiff2pdf in expectation to find vulnerabilities there, however ended up finding vulnerabilities in the fuzzer itself.

Actually, I was not able to fuzz tiff2pdf at all (with an initial corpus of 216 files whose sizes are around 200 bytes), since it crashed and caused a segmentation fault, as you can see at [6].

The crash that we have is at [1], where a negative (too big) length is passed to memcpy. Why does it happen? At line [2] the input is indeed sanitized by ignoring differences that are smaller or equal to 2.
However, `len` is of type `size_t` whereas `del_loc` is of type `int`, therefore `len-del_loc` is unsigned and thus, it fails to check for locations that are higher than `len`.
The reason why the location is even higher than the length is due to an other bug, namely due to an uninitialized memory error. 
The location table is allocated as `int loc[10000];`, however left uninitialized. Then, the input is parsed at [3]. Unfortunately, at [4], the length of loc is expected to have 1024 or more entries, hence it will read garbage if there are too few.

Moreover, trying to launch neuzz on the supplied testset would produce a mess in the directory, as shown at [5]. I haven't analyzed the cause of this yet. Note that I followed exactly the described steps to reproduce the results.

Kindly let me know if you require further information or help.

Best,
Andy Nguyen from ETH Zurich

[1] https://github.com/Dongdongshe/neuzz/blob/master/neuzz.c#L1318
[2] https://github.com/Dongdongshe/neuzz/blob/master/neuzz.c#L1312
[3] https://github.com/Dongdongshe/neuzz/blob/master/neuzz.c#L1871
[4] https://github.com/Dongdongshe/neuzz/blob/master/neuzz.c#L1310
[5] https://imgur.com/a/vvKB7HP

[6] Stack backtrace

```
Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
522     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:522
#1  0x00005555555589a9 in gen_mutate ()
#2  0x000055555555ea05 in fuzz_lop.constprop ()
#3  0x000055555555f667 in start_fuzz ()
#4  0x0000555555555f5e in main ()
(gdb) ir
rax            0x5555558198c3   93824995137731
rbx            0x555555795a60   93824994597472
rcx            0x555555761047   93824994381895
rdx            0xfffffffffff4945d       -748451
rsi            0x555555817c0a   93824995130378
rdi            0x5555558198c3   93824995137731
rbp            0x33     0x33
rsp            0x7fffffffdea8   0x7fffffffdea8
r8             0x9      9
r9             0x555555762d00   93824994389248
r10            0x5555558166a4   93824995124900
r11            0x555555818e09   93824995134985
r12            0x55555578be20   93824994557472
r13            0xb2b08e9c       2997915292
r14            0x801    2049
r15            0xa67    2663
rip            0x7ffff7b72e4b   0x7ffff7b72e4b <__memmove_avx_unaligned_erms+891>
eflags         0x10286  [ PF SF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
---Type <return> to continue, or q <return> to quit---                          fs             0x0      0
gs             0x0      0
(gdb) 
```

**Comment by Dongdongshe** [comment]
Hi Andy,

Thank you for pointing out the potential bugs in Neuzz. Sorry about the inconvenience caused by the bugs. Please also note that current version of Neuzz is still a academic prototype fuzzer. We used some lazy and not safe implementations like a hard-coded 10,000 bytes buffer and 1024 location entries and tested it on 10 real world programs. If you want to try current version of Neuzz on a new program, you may need to slightly change some hard-coded parameters. We are still working on a more stable version of Neuzz and will release soon.

As for the messy junk files in the directory, it is actually not a bug. These junk files are output files of miniunz program which will decompress a ZIP file. If you run AFL on the same binary, you will notice the same messy junk files. It may be annoying to find the working directory filled with junk files. We will add more detail description/warning of zlib case. For other 9 real-world programs provided in this repo, they will definitely not mess your working directory and you are welcome to try them on Neuzz. 

Thank you
Dongdong

**Comment by TheOfficialFloW** [comment]
Hi Dongdong,

Sorry to hijack this issue for a different question - I couldn't find your mail anywhere.

We have evaluated your tool along with AFL and Angora, and unfortunately, it doesn't show the suggested behaviour. While both NEUZZ and Angora have a better start, AFL outperforms them after a while, as you can see below. 

![libarchive](https://user-images.githubusercontent.com/14246466/57628479-500db600-759a-11e9-9ba9-70cd3eaeb517.png)
![libjpeg](https://user-images.githubusercontent.com/14246466/57628480-500db600-759a-11e9-8100-8156ae9f0d5f.png)
![libtiff](https://user-images.githubusercontent.com/14246466/57628481-50a64c80-759a-11e9-9815-f34c0c5c546e.png)
![lz4](https://user-images.githubusercontent.com/14246466/57628484-50a64c80-759a-11e9-9a60-49a57425fb90.png)

May you kindly let us know how you have obtained the results shown on page 10/11?
More specifically, what metrics were you looking at? The AFL edge coverage bitmap?
Furthermore, can you explain why the y-intercept is at point zero for all graphs? Since NEUZZ takes the output queue of 1h AFL training, the inital edge coverage should begin with a higher amount. Or does it only represent newly found edges?

Looking forward to your answers and again sorry to hijack this thread.

Best,
Andy

**Comment by Dongdongshe** [comment]
Hi Andy,

My email is dongdong at cs.columbia.edu. We can discuss it in email.

**Comment by TheOfficialFloW** [comment]
Has anybody been able to reproduce the results at all? Two researchers already contacted me after I filed in this issue and shared the same experience. Namely that neuzz doesn't perform as suggested in the paper, not even on the supplied testcases.

Thanks.

**Comment by sumanj** [comment]
Hi,

Many people have already reproduced the results with our test cases.
Note that you are trying new programs than the ones we tried. As a
common courtesy, you might want to ask the two researchers to contact
us. If you are trying the programs that we tried and not getting the
reported results, you should provide more details about your setup
than this sort of generic comments.

Suman

**Comment by Dongdongshe** [comment]
Hi Andy,

Many other groups have reproduced the results with our test cases. As for the two researchers who shared the same experience with you, did you mean David from Prof. Bacchelli's group? 

If so, just FYI, David has already sent me emails about his experiment details. He tried 3 three programs, zlib, mupdf and objdump and could reproduce the results except mupdf (his results are attached below). The mupdf case is because a latest commit of Neuzz which somehow hurts the performance on Mupdf.(Thanks David for pointing out this issue)
![objdump](https://user-images.githubusercontent.com/9389471/60047297-5d3cbb00-9697-11e9-9683-0b8c8eafefea.png)
![zlib](https://user-images.githubusercontent.com/9389471/60047299-5f067e80-9697-11e9-8818-f0168b4febad.png)
![mupdf](https://user-images.githubusercontent.com/9389471/60047302-6037ab80-9697-11e9-8a2a-feaf1eba9cc0.png)
 I rolled back Neuzz to older version and successfully reproduced the results on Mupdf. I also sent the code to David and waited for his feedback now.

If the two researchers your were mentioning are not David, could you kindly forward their email to me and I am willing to them fix their issue?

Btw, if you are trying new programs, note that it might require some manual tuning when collecting training datasets and setting up Neuzz mutation parameters. This is beyond reproducing the results, but I am happy to help.

Thank you
Dongdong

**Comment by Puzzor** [comment]
Hi Dongdong,

I am one of the two researchers.

First, thank you very much for your good work:) I'm very interested in it. 

Unfortunately we cannot reproduce the experiment part in your paper, I don't know if we did it wrong,what I tried is libxml and libjpeg. Our experiment is based on the latest version of neuzz. The steps of our experiment is as follows:

1. Use the case you provided in this repro, I mean the cases in 'neuzz_in' folder, we didn't change it.

2. Copy the afl-showmap, nn.py,neuzz to the libjpeg and libxml folders under "programs"

3. Compile the latest afl-2.52b, copy the cases under "neuzz_in" to a new "in" folder, and create an "out" folder to run afl later.

4. Run as the README.md says, after an hour, stop it.

5. Run afl with the same seeds for another hour, then stop it.

6. Write a simple script to calculate all the different edges with afl-showmap: the basic command is : "./afl-showmap -q -e -o /dev/stdout -- ./xmllint case", for each case we use that command to calculate the edges and we can finally get the total unique edges. We calculated the edges of the cases under "seeds" folder for  neuzz and "queue" folder under afl. After an hour, we found that the total edges of AFL is higher than neuzz. Sorry that we didnt test it for a long time, just one hour. I don't know if we did it wrong? Or if we ran a longer period of time, the result should be better?

We also meet some problems and questions, thank you very much in advance if you can help:

1.  We nearly cannot run on new cases,especially for libxml, I mean cases(seeds), not program. We often encountered 2 kinds of problems when running it with our own seeds(just simple seeds from the Internet, nothing special): one is stuck, the program will get stuck and we dont know where goes wrong. the second is OOM problem(we can understand why this happens). We notice you mentioned we should just run one seed with afl for an hour, but what if we just use a few cases from the internet? Why we should run them under afl first? 

2. I have the same question with Andy: 
"why the y-intercept is at point zero for all graphs? Since NEUZZ takes the output queue of 1h AFL training, the inital edge coverage should begin with a higher amount. Or does it only represent newly found edges?"

3. We see that the training process is long,(we use Tesla P100 so it shouldn't be our hardware problem), I noticed that the epochs in your code is set to 100, but in your paper is 50, I think that will slow down the training process. Is there any other different part between your description in your paper and the code in this github? 

Thank you very much for your kind help:)

Best regards,
Puzzor

**Comment by Dongdongshe** [comment]
Hi Puzzor,

Thanks for for feedback. I checked your experiments setup and it seems correct. Could you share the detail log of Neuzz of both NN module and fuzzing module with me, so I could take a closer look at your experiment setting? (you just need to save the stdout of nn.py and neuzz). 

One minor thing is that for step 6, you should be careful with -m(memory usage) and -t(timeout) parameters of afl-showmap. When running some inputs of tested binary under afl-showmap, it would cause stuck or OOM(false postive because the default memory limit is only 50MB). A suggested paratermets is -m 512 -t 500. Another simple and fast way to do that is that you can simply check Neuzz's output, the last line will show current edge coverage. Similarly, for AFL, you can find map density number from AFL's GUI and multiply it with 65536. 

For your questions: 
1. "We nearly cannot run on new cases,especially for libxml". Do you mean you fed a XML file downloaded from Internet(not from Neuzz_in) to xmllint and fount it got stuck or OOM in a common run? I am not sure why this happened. The xmllint should be able to parse some simple XML files. "We notice you mentioned we should just run one seed with afl for an hour, but what if we just use a few cases from the internet? Why we should run them under afl first?" This suggestion is only for trying a new programs and collecting the training data by yourself. If you just want to reproduce the results, you could ignore it.

2. The number is New edge coverage, computed by total edge coverage - total seeds coverage.

3. On my environment (Nvidia 1080Ti), the training takes around 1 or 2 minutes(100 epochs) which is pretty fast. Your GPU is more powerful than mine, the training should take less time. Could you send me the output of nn.py, so I could take a look at details of the training on your machine?

Thank you
Dongdong
