### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by Palashio** [Dongdongshe/neuzz#3]
I'm currently trying to run neuzz on the readelf program and keeping getting this error: Unable to execute programs/readelf/readelf

1. Ubuntu 18.0.4
2. Installed tensorflow, and keras using pip

3. Then I built neuzz using this line: 

gcc -O3 -funroll-loops ./neuzz.c -o neuzz

Now, when I open two terminals and run 

python nn.py ./readelf -a 

in one of them, and

 ./neuzz -i neuzz_in -o seeds -l 7506 ./readelf -a @@  

in another, I get an error that says that the readelf file is not executable. I've checked the properties of it, and it says that it is executable.

**Comment by Dongdongshe** [comment]
Hi Palashio,

It seems your issue is because the missing dependency of 32 bit library. The readelf is built into 32 bit. Please follow the tutorial in this link to install the dependency library. https://github.com/Dongdongshe/neuzz/blob/master/programs/readelf/README.md. If you still encounter any issue, please let me know.

**Comment by Palashio** [comment]
@Dongdongshe 

I tried this right after I got the error. But for some reason, every time I attempted to move the neuzz folder or any of its parts into the cpu folder with this line

cp -a /home/name/neuzz /sys/devices/system/cpu

It returned an error saying that I do not have permission to do this.

**Comment by Dongdongshe** [comment]
You don't need to copy the neuzz binary to /sys/devices/system/cpu folder since it is a crucial system configuration folder. I think your issue is because unclear instructions for step 3 in  https://github.com/Dongdongshe/neuzz/blob/master/programs/readelf/README.md. Sorry about the confusion. For step 3, please use the follow command to copy three files to your working directory (/path_to_neuzz/programs/readelf).
cp /path_to_neuzz/neuzz /path_to_neuzz/programs/readelf
cp /path_to_neuzz/nn.py  /path_to_neuzz/programs/readelf
cp /path_to_neuzz/alf-showmap /path_to_neuzz/programs/readelf

BTW, did you fix the "unable to execute" issue by installing the dependency library?

**Comment by Palashio** [comment]
I just did that thank you! 

Although, I still receive this error message: 

```
[-] PROGRAM ABORT : Unable to execute './readelf'
         Location : run_target(), afl-showmap.c:329
```
When I went through the tutorial to setup the 32 bit and reached step 2, I was unable to run this line

echo performance | tee cpu*/cpufreq/scaling_governor

an error was returned that said there was no directory called performance. After looking through my cpu folder under /sys/devices/system/cpu, I couldn't find performance or scaling_governer anywhere. Here's my cpu directory: 

![image](https://user-images.githubusercontent.com/35114859/53690045-10705580-3d31-11e9-9129-719ab010cfe6.png)

There's nothing inside of the cpufreq folder, and cpu0 and cpu1 don't have cpufreq or scaling_governer inside of them.

**Comment by Dongdongshe** [comment]
The error message actually comes from afl-showmap. It means the execv() fails to run binary 'readelf'. Two step I would suggest you to do. 
1. make sure the readelf you are testing is directly from neuzz repo. 2. check if you could successfully run the binary "readelf" under your current system. (run ./readelf -a [a tested file] under your terminal)
You issue seems to be caused by the failure to execute the tested binary, not in the neuzz code logic. 

For step 2, you can skip it since they are only used for performance optimization.

**Comment by Palashio** [comment]
I'm able to successfully run readelf and the readelf i'm testing is directly from the repo (copied through git clone). 

Here are the results of both terminals when I attempt to start NN and NEUZZ module.

![image](https://user-images.githubusercontent.com/35114859/53690413-09007a80-3d38-11e9-90cd-6b977a106306.png)

![image](https://user-images.githubusercontent.com/35114859/53690439-36e5bf00-3d38-11e9-8fa7-72c7ef83a788.png)


Here's what I get when I run readelf -a:

![image](https://user-images.githubusercontent.com/35114859/53690444-5da3f580-3d38-11e9-8ed0-f722d0162307.png)

**Comment by sumanj** [comment]
you should try "./readelf -a" not "readelf -a". You do understand the notion of PATH variable, right?

**Comment by Palashio** [comment]
@sumanj thanks so much for the help; it worked.
