### ISSUE TITLE
not able to understand 

### ISSUE THREAD

**Issue by f1reburner** [Dongdongshe/neuzz#4]
This is more a question about understanding the program. After running both 

python nn.py ./readelf -a
./neuzz -i neuzz_in -o seeds -l 7506 ./readelf -a @@  

The program succesfully runs. What does the accuracy that is presented during and after each epoch concretely represent? Couldn't seem to understand from your paper.

**Comment by Dongdongshe** [comment]
The accuracy is a customized metric for multiple label classification model. A common accuracy metric is computed by (total number of correct prediction labels)/(total number of labels). The equation can be further shown as (total number of correct prediction label of 1 + total number of correct prediction of label 0) / (total number of correct prediction label of 1 + total number of correct prediction of label 0 + total number of wrong prediction). 

In practice, we find that (total number of correct prediction of label 0) is greater than (total number of correct prediction of label 1) because (the total number of ground truth of label 0) is greater than the (the total number of ground truth of label 1). For example, for a model with 3400 edges, a normal execution would only cover 1200 edges.(that is total number of ground truth label 0 is 2200, the total number of ground truth label 1 is 1200). To more clearly show the model accuracy improvement (rather than lazily predicting label 0), we use  (total number of correct prediction label of 1) / (total number of correct prediction label of 1 + total number of wrong prediction) to compute the accuracy. Note that, it is just a customized metric to evaluate the accuracy. The accuracy metric would not affect the model training since the loss function is still the multiple cross entropy as shown in the paper.

**Comment by f1reburner** [comment]
Thank you that helps alot! Additionally, what does it mean in the context of fuzzing? For example, for the program objdump what does a 0.9254 accuracy mean?

**Comment by Dongdongshe** [comment]
It means the training accuracy for current neural program model is 0.9245. In general, the higher accuracy represents a better fit of neural program model. For features number, that is only debugging, and the 16997.86 number is the time elapsed( which can be easily figured out by reading the source code, please check the code for more detail).

**Comment by f1reburner** [comment]
I meant as in does the 0.9245 represent the accuracy at which the training data is generated or the accuracy at which the program vulnerabilities are modeled.

I read your paper, and still couldn't grasp what this specific accuracy meant.

**Comment by Dongdongshe** [comment]
The accuracy represents training accuracy for neural network model which models program behaviors by predicting the edge coverage given a specified input. To be specific, given a NN model and a set of inputs, the correct edge coverage prediction is 0.9245 (that is 92.45% of edge coverage is predicted correctly).

**Comment by f1reburner** [comment]
do you happen to know how to assign the training to a GPU from the linux terminal?

**Comment by Dongdongshe** [comment]
You probably need to install tensorflow-gpu rather than tensorflow. If you have any further question of running the code, please reach me through the email. The issue is for reporting the bug of code.
