### ISSUE TITLE
please resolve this

### ISSUE THREAD

**Issue by akshaya-24** [Dongdongshe/neuzz#9]
![image](https://user-images.githubusercontent.com/28007901/55133004-362f2580-514a-11e9-976b-e17fb8866827.png)
![image](https://user-images.githubusercontent.com/28007901/55133018-41825100-514a-11e9-94e7-d8424589aff5.png)

I am getting this issue. what do i have to do to resolve it.

**Comment by Dongdongshe** [comment]
The fuzzing module command is not complete, it misses symbol "@@" at the end. It should be ./neuzz -i neuzz_in -o seeds -l 75 ./code @@.

You need more training samples to feed into NN model. Currently you only feed TWO samples to a NN model, which is too small for training. The reason for NN module crash is that NN module would not consider crash inputs as training samples and you passed two crash inputs in the training data which result in empty training corpus. We do not include crash inputs in the training corpus because all the inputs in the training corpus will be possibly used as seeds to generate a large number of mutations and the mutations from a crash input would simply lead to the already known crash.

I would suggest you to collect more training data by run afl-fuzz for a while, say an hour. If you want to include crash inputs into training data, simply copy nn.py 85-89 right after nn.py 84.

**Comment by akshaya-24** [comment]
okay thanks. May I know why the error 'cannot open file grandient_info_p' occurs?

**Comment by akshaya-24** [comment]
![image](https://user-images.githubusercontent.com/28007901/55213109-4d3c4900-5218-11e9-81d6-03da7c7b1c25.png)
![image](https://user-images.githubusercontent.com/28007901/55213113-5200fd00-5218-11e9-8c1e-866b14111455.png)

We ran afl and collected training data and copied queue folder to neuzz_in. Even after running we are getting same error. Gradient_info_p file not found.

**Comment by Dongdongshe** [comment]
The error is caused by early termination of nn.py. File 'gradient_info_p' is generated in function gen_mutate2(), which is called AFTER process_data(). From your error message, nn.py crashed because an empty np array is passed to np.unique(). 

I would suggest to check the shape of the np array bitmap. It seems all the inputs in your corpus are not properly processed into np array.
